image: node:12

before_script:
  - npm install -g eslint
  - npm ci

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - npm run lint

# LTS
test:node:12:
  script:
    - npm run clean
    - npm run build
    - npm test

test:node:11:
  image: node:11
  script:
    - npm run clean
    - npm run build
    - npm test

# LTS
test:node:10:
  image: node:10
  script:
    - npm run clean
    - npm run build
    - npm test
